# Project Information
site_name: DeepGorthi Notes
site_description: 'All things DevOps, Infrastructure, Linux and networking'
site_author: 'Pradeep Gorthi'
site_url: 'https://docs.deepgorthi.com'

theme:
  name: 'material'
  custom_dir: custom_theme/
  language: 'en'
  palette:
    primary: 'deep orange'
    accent: 'deep orange'
  logo: 'img/icon.png'
  # logo:
  #   icon: 'local_library'
  # font:
  #   text: 'Ubuntu'
  #   code: 'Ubuntu Mono'
  feature:
    tabs: true
  favicon: 'img/favicon.png'
extra:
  search:
    tokenizer: '[\s\-\.]+'

repo_name: 'deepgorthi/dg-notes'
repo_url: 'https://github.com/deepgorthi/dg-notes'

markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - meta
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/deepgorthi'
    - type: 'twitter'
      link: 'https://twitter.com/deepgorthi'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/deepgorthi'

# Google Analytics
google_analytics:
  - 'UA-153019680-1'
  - 'auto'

# Copyright
copyright: 'Content Copyright &copy; Pradeep Gorthi'