# Project Information
site_name: DeepGorthi Notes
site_description: 'All things DevOps, Infra, Linux and networking'
site_author: 'Pradeep Gorthi'
site_url: 'https://docs.deepgorthi.com'

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'deep orange'
    accent: 'deep orange'
  # logo: 'images/logo.svg'
  logo:
    icon: 'local_library'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  feature:
    tabs: true
  # favicon: 'favicon.ico'
extra:
  search:
    tokenizer: '[\s\-\.]+'

repo_name: 'deepgorthi/dg-notes'
repo_url: 'https://github.com/deepgorthi/dg-notes'

markdown_extensions:
  - toc:
      permalink: true

markdown_extensions:
  - footnotes

markdown_extensions:
  - meta

markdown_extensions:
  - admonition
markdown_extensions:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Customization
extra:
  # manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/deepgorthi'
    - type: 'twitter'
      link: 'https://twitter.com/deepgorthi'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/deepgorthi'

# Google Analytics
# google_analytics:
#   - 'UA-XXXXXXXX-X'
#   - 'auto'

# Copyright
copyright: 'Copyright &copy; Pradeep Gorthi'