site_name: My Docs
theme:
  name: 'material'
  palette:
    primary: 'deep orange'
    accent: 'deep orange'
#  logo: 'images/logo.svg'
  logo:
    icon: 'local_library'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  # feature:
  #   tabs: true
extra:
  search:
    tokenizer: '[\s\-\.]+'

repo_name: 'squidfunk/mkdocs-material'
repo_url: 'https://github.com/squidfunk/mkdocs-material'