---
# tasks file for roles/webservers
- name: Upload index file
  copy: 
    src: ../files/index.php
    dest: "{{ path_to_app }}"
    mode: 0755

- name: Configure php.ini file
  lineinfile: # Change a line in a config file matching the regex to the line value.
    path: /etc/php.ini
    regexp: ^short_open_tag
    line: 'short_open_tag=Off'
  notify: restart apache